version: '3'

services:
  web:
    image: yashguj20/node-todo-cicd-image:latest
    container_name: node-todo-app
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
    networks:
      - app-network
    restart: always  # Optional: Ensures the container restarts if it crashes

networks:
  app-network:
    driver: bridge
